---
title: "p8105_hw1_pw2551"
author: "Paula Wu"
date: "9/23/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
# I set message = FALSE for concision
library(tidyverse)
```

### **Problem 1**:
```{r}
set.seed(1) 
p1_df = tibble(
  vec_numeric = rnorm(10),
  vec_logical = vec_numeric > 0,
  vec_char = c("will", "you", "get", "a", 
                 "headache", "if", "you", "think", "too", "hard"),
  vec_factor = factor(c("high", "low", "medium", "high", "medium", 
                        "medium", "low", "high", "high", "low"))
)
p1_df
```
```{r, collapse = TRUE}
#take the mean of each variable
mean(pull(p1_df, vec_numeric))
mean(pull(p1_df, vec_logical))
mean(pull(p1_df, vec_char))
mean(pull(p1_df, vec_factor))
```

```{r, eval = FALSE}
vec_logical_num = as.numeric(vec_logical)
vec_char_num = as.numeric(vec_char)
vec_factor_num = as.numeric(vec_factor)
```

### **Problem 2**:
```{r}
# packages installed in the terminal
data("penguins", package = "palmerpenguins")
penguins
```

Variable names: `r variable.names(penguins)`. <br>
For this penguins dataset, there are `r nrow(penguins)` rows 
and `r ncol(penguins)` columns. <br>
The flipper length (mm) is 
`r mean(pull(penguins, 'flipper_length_mm'), na.rm = TRUE)`

```{r}
bill_len = pull(penguins, bill_length_mm)
flip_len = pull(penguins, flipper_length_mm)
species_color = pull(penguins, species)
ggplot(penguins, aes(x = bill_len, y = flip_len, col = species_color)) + 
  geom_point() + 
  ggtitle("Flipper and Bill Length for Penguins") +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(y = "Flipper Length (mm)",x = "Bill Length (mm)")
```
